version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:5.0.17-ubuntu2004
    container_name: mongo_new
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} # 기본 관리자 계정의 사용자 이름
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # 기본 관리자 계정의 비밀번호
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - db-data:/mongo
      - ${MONGO_KEY_FILE}:/etc/mongodb.key
    command: 'mongod --replSet myReplicaSet --keyFile /etc/mongodb.key --bind_ip_all'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"  # AMQP 포트
      - "61613:61613"  # STOMP 포트
      - "15672:15672"  # 관리 UI 포트

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일
    ports:
      - "9090:9090"  # Prometheus 웹 인터페이스 포트
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana 웹 인터페이스 포트
    environment:
      - GF_SECURITY_ADMIN_USER=admin     # Grafana 기본 사용자 이름
      - GF_SECURITY_ADMIN_PASSWORD=admin # Grafana 기본 비밀번호
    networks:
      - monitoring-network

  app1:
    build: .
    image: cubetalk-server:1.0
    container_name: spring-app1-container
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}/${MONGO_DB_NAME}?retryWrites=true&w=majority
      API_URL: "http://host.docker.internal:8080"

  app2:
    image: cubetalk-server:1.0
    container_name: spring-app2-container
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}/${MONGO_DB_NAME}?retryWrites=true&w=majority


  app3:
    image: cubetalk-server:1.0
    container_name: spring-app3-container
    ports:
      - "8083:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}/${MONGO_DB_NAME}?retryWrites=true&w=majority

volumes:
  db-data:
networks:
  monitoring-network:
    driver: bridge